//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperDrive.Core.UI {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperDrive.Core.UI.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string BtnCancelSelect {
            get {
                return ResourceManager.GetString("BtnCancelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string BtnConfirm {
            get {
                return ResourceManager.GetString("BtnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string BtnImage {
            get {
                return ResourceManager.GetString("BtnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string BtnOpen {
            get {
                return ResourceManager.GetString("BtnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry 的本地化字符串。
        /// </summary>
        internal static string BtnRetry {
            get {
                return ResourceManager.GetString("BtnRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        internal static string BtnReturn {
            get {
                return ResourceManager.GetString("BtnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        internal static string BtnSelect {
            get {
                return ResourceManager.GetString("BtnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string BtnSelectAll {
            get {
                return ResourceManager.GetString("BtnSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get 的本地化字符串。
        /// </summary>
        internal static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting 的本地化字符串。
        /// </summary>
        internal static string Getting {
            get {
                return ResourceManager.GetString("Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse failed 的本地化字符串。
        /// </summary>
        internal static string MsgBrowseFailed {
            get {
                return ResourceManager.GetString("MsgBrowseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select at least one device 的本地化字符串。
        /// </summary>
        internal static string MsgChooseAtLeastOneDevice {
            get {
                return ResourceManager.GetString("MsgChooseAtLeastOneDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No device found. Please run SuperDrive on your devices. 的本地化字符串。
        /// </summary>
        internal static string MsgNoDevice {
            get {
                return ResourceManager.GetString("MsgNoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select file then send 的本地化字符串。
        /// </summary>
        internal static string MsgSelectFile {
            get {
                return ResourceManager.GetString("MsgSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending 的本地化字符串。
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single tap to select/deselect, Double tap to open file or folder 的本地化字符串。
        /// </summary>
        internal static string TipsSelectopen {
            get {
                return ResourceManager.GetString("TipsSelectopen", resourceCulture);
            }
        }
    }
}
